{
 "title": "Syncthing",
 "tags": [
  "nixos",
  "syncthing"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Syncthing up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "syncthing_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connected devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "syncthing_connected_devices", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Folder status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "syncthing_folder_state", "legendFormat": "{{instance}} / {{folder}}" }
   ]
  },
  {
   "title": "Out of sync files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "syncthing_folder_need_files", "legendFormat": "{{instance}} / {{folder}}" }
   ]
  },
  {
   "title": "Syncthing logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"syncthing.service\"}"
    }
   ]
  }
 ]
}