{ config, ... }:

{
  home.file.".config/btop/themes/catppuccin_mocha.theme".text = ''
    # Catppuccin Mocha theme for btop++
    theme[main_bg]="#1e1e2e"
    theme[main_fg]="#cdd6f4"
    theme[title]="#cdd6f4"
    theme[hi_fg]="#89b4fa"
    theme[selected_bg]="#313244"
    theme[selected_fg]="#cdd6f4"
    theme[inactive_fg]="#6c7086"
    theme[graph_text]="#f5e0dc"
    theme[meter_bg]="#313244"
    theme[proc_misc]="#cdd6f4"
    theme[cpu_box]="#89b4fa"
    theme[mem_box]="#a6e3a1"
    theme[net_box]="#fab387"
    theme[proc_box]="#cba6f7"
    theme[div_line]="#6c7086"
    theme[temp_start]="#a6e3a1"
    theme[temp_mid]="#f9e2af"
    theme[temp_end]="#f38ba8"
    theme[cpu_start]="#89b4fa"
    theme[cpu_mid]="#cba6f7"
    theme[cpu_end]="#f38ba8"
    theme[free_start]="#f38ba8"
    theme[free_mid]="#fab387"
    theme[free_end]="#a6e3a1"
    theme[cached_start]="#f38ba8"
    theme[cached_mid]="#fab387"
    theme[cached_end]="#a6e3a1"
    theme[available_start]="#f38ba8"
    theme[available_mid]="#fab387"
    theme[available_end]="#a6e3a1"
    theme[used_start]="#f38ba8"
    theme[used_mid]="#fab387"
    theme[used_end]="#a6e3a1"
    theme[download_start]="#a6e3a1"
    theme[download_mid]="#89b4fa"
    theme[download_end]="#cba6f7"
    theme[upload_start]="#f38ba8"
    theme[upload_mid]="#fab387"
    theme[upload_end]="#f9e2af"
    theme[process_start]="#89b4fa"
    theme[process_mid]="#cba6f7"
    theme[process_end]="#f38ba8"
  '';

  home.file.".config/btop/btop.conf" = {
    text = ''
      color_theme = "${config.home.homeDirectory}/.config/btop/themes/catppuccin_mocha.theme"
      theme_background = False
      truecolor = True
      force_tty = False
      presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
      vim_keys = True
      rounded_corners = True
      graph_symbol = "braille"
      graph_symbol_cpu = "default"
      graph_symbol_gpu = "default"
      graph_symbol_mem = "default"
      graph_symbol_net = "default"
      graph_symbol_proc = "default"
      shown_boxes = "cpu mem net proc"
      update_ms = 2000
      proc_sorting = "pid"
      proc_reversed = False
      proc_tree = False
      proc_colors = True
      proc_gradient = True
      proc_per_core = True
      proc_mem_bytes = True
      proc_cpu_graphs = True
      proc_info_smaps = False
      proc_left = False
      proc_filter_kernel = False
      proc_aggregate = False
      cpu_graph_upper = "Auto"
      cpu_graph_lower = "Auto"
      show_gpu_info = "Auto"
      cpu_invert_lower = True
      cpu_single_graph = False
      cpu_bottom = False
      show_uptime = True
      show_cpu_watts = True
      check_temp = True
      cpu_sensor = "Auto"
      show_coretemp = True
      cpu_core_map = ""
      temp_scale = "celsius"
      base_10_sizes = False
      show_cpu_freq = True
      clock_format = "%X"
      background_update = True
      custom_cpu_name = ""
      disks_filter = ""
      mem_graphs = True
      mem_below_net = False
      zfs_arc_cached = True
      show_swap = True
      swap_disk = True
      show_disks = True
      only_physical = True
      use_fstab = True
      zfs_hide_datasets = False
      disk_free_priv = False
      show_io_stat = True
      io_mode = True
      io_graph_combined = False
      io_graph_speeds = ""
      net_download = 100
      net_upload = 100
      net_auto = True
      net_sync = True
      net_iface = "enp34s0"
      base_10_bitrate = "Auto"
      show_battery = True
      selected_battery = "Auto"
      show_battery_watts = True
      log_level = "WARNING"
      nvml_measure_pcie_speeds = True
      rsmi_measure_pcie_speeds = True
      gpu_mirror_graph = True
      custom_gpu_name0 = ""
      custom_gpu_name2 = ""
      custom_gpu_name3 = ""
      custom_gpu_name4 = ""
      custom_gpu_name5 = ""
    '';
  };
}
